(function(g){var window=this;'use strict';var z6=function(a){g.W.call(this,{D:"div",K:"ytp-inline-preview-ui"});this.pe=!1;this.player=a;this.S(a,"onStateChange",this.DH);this.S(a,"videodatachange",this.El);this.S(a,"onInlinePreviewModeChange",this.dU);this.Sd=new g.xq(this.Gq,null,this);g.J(this,this.Sd)},A6=function(a){g.tM.call(this,a);
this.i=new z6(this.player);g.J(this,this.i);this.i.hide();g.fM(this.player,this.i.element,4);a.isInline()&&(this.load(),g.M(a.getRootNode(),"ytp-inline-preview-mode",!0),this.player.T().L("web_inline_player_disable_scrubbing")&&g.M(a.getRootNode(),"ytp-inline-preview-mode-no-scrubbing",!0))};
g.v(z6,g.W);g.h=z6.prototype;
g.h.sF=function(){this.tooltip=new g.jQ(this.player,this);g.J(this,this.tooltip);g.fM(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Ac=new g.mN(this.player);g.J(this,this.Ac);var a=["ytp-inline-preview-scrim"];this.player.T().L("web_inline_player_expand_to_watch")||a.push("ytp-inline-preview-scrim-clear");this.Hg=new g.W({D:"div",Ga:a});g.J(this,this.Hg);this.Hg.Ca(this.element);this.S(this.Hg.element,"click",this.UA);this.player.T().L("web_inline_player_expand_to_watch")&&(a=new g.$1(this.player,
this),g.J(this,a),a.Ca(this.Hg.element));this.Kg=new g.WP(this.player,this);g.J(this,this.Kg);this.Kg.Ca(this.Hg.element);this.controls=new g.W({D:"div",K:"ytp-inline-preview-controls"});g.J(this,this.controls);this.controls.Ca(this.element);a=new g.HO(this.player,this);g.J(this,a);a.Ca(this.controls.element);a=new g.UP(this.player,this);g.J(this,a);a.Ca(this.controls.element);this.Jc=new g.UO(this.player,this);g.J(this,this.Jc);g.fM(this.player,this.Jc.element,4);this.S(this.player,"appresize",this.yb);
this.S(this.player,"fullscreentoggled",this.yb);this.yb()};
g.h.show=function(){g.yq(this.Sd);this.pe||(this.sF(),this.pe=!0);0!==this.player.getPlayerState()&&g.W.prototype.show.call(this);this.Jc.show()};
g.h.hide=function(){this.Sd.stop();g.W.prototype.hide.call(this);this.player.isInline()||this.pe&&this.Jc.hide()};
g.h.ra=function(){g.W.prototype.ra.call(this)};
g.h.UA=function(a){a.target!==this.Hg.element||this.player.T().L("web_inline_player_expand_to_watch")||this.player.Oa("onExpandInlinePreview",a)};
g.h.dU=function(){g.M(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.h.Cd=function(){this.Jc.Sb();this.Kg.Sb()};
g.h.Gq=function(){this.Cd();g.yq(this.Sd)};
g.h.yb=function(){g.hP(this.Jc,0,this.player.bb().getPlayerSize().width,!1);g.VO(this.Jc)};
g.h.DH=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.h.El=function(a,b){this.player.isInline()&&g.M(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.cG)};
g.h.hc=function(){return this.tooltip};
g.h.Ye=function(){return!1};
g.h.Bf=function(){return!1};
g.h.Gi=function(){return!1};
g.h.Px=function(){};
g.h.Jn=function(){};
g.h.Ks=function(){};
g.h.Yn=function(){return null};
g.h.uw=function(){return null};
g.h.Ej=function(){return new g.$m(0,0,0,0)};
g.h.handleGlobalKeyDown=function(){return!1};
g.h.handleGlobalKeyUp=function(){return!1};
g.h.Nq=function(a,b,c,d,e){var f=d=0,k=0,l=g.Dn(a);if(b){c=g.Fq(b,"ytp-miniplayer-expand-watch-page-button");var m=g.Fq(b,"ytp-mute-button"),n=g.Fq(b,"ytp-subtitles-button"),p=g.Bn(b,this.element);b=g.Dn(b);d=p.y+40;c&&(k=8);if(n||m)k=p.x-l.width+b.width}else k=c-l.width/2,f=35;b=this.player.bb().getPlayerSize().width;k=g.Wg(k,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=k+"px"};
g.h.showControls=function(){};
g.h.Cl=function(){};
g.h.Tk=function(){return!1};g.v(A6,g.tM);A6.prototype.dj=function(){return!1};
A6.prototype.load=function(){this.player.hideControls();this.i.show()};
A6.prototype.unload=function(){this.player.showControls();this.i.hide()};g.sM("inline_preview",A6);})(_yt_player);
